### PR TITLE
Revert "Added LightVisual (#202)"

### LINKED ISSUE #226: OgreLightVisual.cc error C2664 cannot convert from 'const char [19]' to 'const Ogre::MaterialPtr &'
Ignition rendering nightly is failing to build on windows which appears to be caused by #202 (@ahcorde FYI)

https://build.osrfoundation.org/job/ign_rendering-ci-win/111/console

```
[453.891s] C:\Jenkins\workspace\ign_rendering-ci-win\ws\ign-rendering\ogre\src\OgreLightVisual.cc(78,58): error C2664: 'void Ogre::SimpleRenderable::setMaterial(const Ogre::MaterialPtr &)': cannot convert argument 1 from 'const char [19]' to 'const Ogre::MaterialPtr &' [C:\Jenkins\workspace\ign_rendering-ci-win\ws\build\ignition-rendering5\ogre\src\ignition-rendering5-ogre.vcxproj]
[453.891s] C:\Jenkins\workspace\ign_rendering-ci-win\ws\ign-rendering\ogre\src\OgreLightVisual.cc(78,58): message : Reason: cannot convert from 'const char [19]' to 'const Ogre::MaterialPtr' [C:\Jenkins\workspace\ign_rendering-ci-win\ws\build\ignition-rendering5\ogre\src\ignition-rendering5-ogre.vcxproj]
[453.891s] C:\Jenkins\workspace\ign_rendering-ci-win\ws\ign-rendering\ogre\src\OgreLightVisual.cc(78,58): message : Constructor for class 'Ogre::SharedPtr<Ogre::Material>' is declared 'explicit' [C:\Jenkins\workspace\ign_rendering-ci-win\ws\build\ignition-rendering5\ogre\src\ignition-rendering5-ogre.vcxproj]
[453.891s] C:\vcpkg\installed\x64-windows\include\OGRE\OgreSimpleRenderable.h(76,22): message : see declaration of 'Ogre::SimpleRenderable::setMaterial' (compiling source file C:\Jenkins\workspace\ign_rendering-ci-win\ws\ign-rendering\ogre\src\OgreLightVisual.cc) [C:\Jenkins\workspace\ign_rendering-ci-win\ws\build\ignition-rendering5\ogre\src\ignition-rendering5-ogre.vcxproj]
[453.891s] C:\Jenkins\workspace\ign_rendering-ci-win\ws\ign-rendering\ogre\src\OgreLightVisual.cc(114,48): error C2664: 'void Ogre::SimpleRenderable::setMaterial(const Ogre::MaterialPtr &)': cannot convert argument 1 from 'std::string' to 'const Ogre::MaterialPtr &' [C:\Jenkins\workspace\ign_rendering-ci-win\ws\build\ignition-rendering5\ogre\src\ignition-rendering5-ogre.vcxproj]
```

### PR DESCRIPTION
**Pull request by sloretz**
This reverts commit f9b58e643da57f60f6f568ca6e79984925539bf3.

Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>

Fixes #226

@ahcorde @iche033 mind taking a look?

### CODE REVIEW

**Comment by ahcorde** [comment]
This PR should fix the problem https://github.com/ignitionrobotics/ign-rendering/pull/228. Let's wait the Windows CI

**Comment by chapulina** [comment]
Closing in favor of #228. Thanks for staying on top of it, :man_farmer: @sloretz
